# see https://raw.githubusercontent.com/yoheimuta/protolint/master/_example/config/.protolint.yaml for all options
lint:
  rules:
    remove:
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - ENUM_FIELD_NAMES_PREFIX
  rules_option:
    max_line_length:
      max_chars: 120
      tab_chars: 2

    indent:
      style: 2
